package com.filebreaker.manager.gui.dialogs;

import java.awt.event.ActionEvent;

import com.filebreaker.manager.controllers.MainController;
import com.filebreaker.manager.gui.frames.ExperimentsFrameView;

public class NewExperimentJDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 8408082753995792194L;

	private javax.swing.JButton createExperimentButton;
    
	private javax.swing.JButton cancelExperimentCreationButton;
    
    private javax.swing.JLabel titleLabel;
    
    private javax.swing.JLabel newExperimentLabel;
    
    private javax.swing.JLabel sampleNumberLabel;
    
    private javax.swing.JSpinner sampleNumberSpinner;
    
    private javax.swing.JTextField experimentNameTextField;
    
    private MainController mainController;
    
    private ExperimentsFrameView experimentsFrameView;
    
    /**
     * Creates new form NewExperimentJDialog
     * @param experimentsFrameView 
     */
    public NewExperimentJDialog(java.awt.Frame parent, boolean modal, MainController mainController, ExperimentsFrameView experimentsFrameView) {
        super(parent, modal);
        
        this.mainController = mainController;
        this.experimentsFrameView = experimentsFrameView;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                         
    private void initComponents() {
        titleLabel = new javax.swing.JLabel();
        newExperimentLabel = new javax.swing.JLabel();
        sampleNumberLabel = new javax.swing.JLabel();
        experimentNameTextField = new javax.swing.JTextField();
        sampleNumberSpinner = new javax.swing.JSpinner();
        createExperimentButton = new javax.swing.JButton();
        cancelExperimentCreationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        titleLabel.setText("Introduce los siguientes datos");

        newExperimentLabel.setText("Nombre del experimento");

        sampleNumberLabel.setText("Número inicial de muestras");
        
        experimentNameTextField.setText("");
        
        createExperimentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/note_new.gif")));
        createExperimentButton.setText("Crear");
        createExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExperimentActionPerformed(evt);
            }
        });

        cancelExperimentCreationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/note_delete.gif")));
        cancelExperimentCreationButton.setText("Cancelar");
        cancelExperimentCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	cancelExperimentCreationActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(newExperimentLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(experimentNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(titleLabel)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(sampleNumberLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                        .add(sampleNumberSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(72, 72, 72)
                .add(createExperimentButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelExperimentCreationButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(newExperimentLabel)
                            .add(experimentNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(sampleNumberLabel)
                        .add(6, 6, 6))
                    .add(sampleNumberSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelExperimentCreationButton)
                    .add(createExperimentButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }
    
    private void createExperimentActionPerformed(ActionEvent evt) {
		String experimentName = experimentNameTextField.getText();
		Integer samplesNumber = (Integer)sampleNumberSpinner.getValue();
		
		mainController.createExperiment(experimentName, samplesNumber);
		this.setVisible(false);
		
		experimentsFrameView.refreshTable();
	}
    
    private void cancelExperimentCreationActionPerformed(ActionEvent evt) {
		this.setVisible(false);
    }
}